# SPDX-FileCopyrightText: 2024 Ledger SAS
#
# SPDX-License-Identifier: Apache-2.0

name: Upload Python Package to jfrog

on:
  release:
    types: [released]

jobs:
  release:
    permissions:
      id-token: write
      contents: read
      attestations: write
    uses: outpost-os/pipeline-python/.github/workflows/publish.yml@main
    with:
      environment: publish
      runner: outpost-os-shared-small
      python-version: '3.10'
      build-name: svd2json-release
      module-name: svd2json
      repo-name: outpost-pypi-prod-public
      virtual-repo-name: outpost-pypi-virtual-green
